<?php
if (! defined ( 'BASEPATH' ))
	exit ( 'No direct script access allowed' );

$config ['method'] = array (
		'admin_image' => array (
				'index' => WEEE_PRIVILEGE_CONFIG,
				'*' => null 
		),
		'event' => array (
				'view' => null,
				'edit' => WEEE_PRIVILEGE_NORMAL,
				'admin' => WEEE_PRIVILEGE_NORMAL,
				'export' => WEEE_PRIVILEGE_NORMAL 
		),
		'weixin' => array (
				'send_template_message' => WEEE_PRIVILEGE_CONFIG 
		) 
);

$config ['privilege'] = array (
		WEEE_PRIVILEGE_ANONYMOUS => array (
				USER_ROLE_ANONYMOUS,
				META_CODE_USER_ROLE_NORMAL_USER,
				META_CODE_USER_ROLE_DEAL_VIEWER,
				META_CODE_USER_ROLE_DEAL_ADMIN,
				META_CODE_USER_ROLE_DEAL_3RD_ADMIN,
				META_CODE_USER_ROLE_PURCHASER,
				META_CODE_USER_ROLE_WAREHOUSE_VIEWER,
				META_CODE_USER_ROLE_WAREHOUSE_KEEPER,
				META_CODE_USER_ROLE_ACCOUNTING,
				META_CODE_USER_ROLE_ARTICLE_ADMIN,
				META_CODE_USER_ROLE_CS_AGENT,
				META_CODE_USER_ROLE_CS_MANAGER,
				META_CODE_USER_ROLE_MANAGER,
				META_CODE_USER_ROLE_SYSTEM_ADMIN 
		),
		WEEE_PRIVILEGE_NORMAL => array (
				META_CODE_USER_ROLE_NORMAL_USER,
				META_CODE_USER_ROLE_DEAL_VIEWER,
				META_CODE_USER_ROLE_DEAL_ADMIN,
				META_CODE_USER_ROLE_DEAL_3RD_ADMIN,
				META_CODE_USER_ROLE_PURCHASER,
				META_CODE_USER_ROLE_WAREHOUSE_VIEWER,
				META_CODE_USER_ROLE_WAREHOUSE_KEEPER,
				META_CODE_USER_ROLE_ACCOUNTING,
				META_CODE_USER_ROLE_ARTICLE_ADMIN,
				META_CODE_USER_ROLE_CS_AGENT,
				META_CODE_USER_ROLE_CS_MANAGER,
				META_CODE_USER_ROLE_MANAGER,
				META_CODE_USER_ROLE_SYSTEM_ADMIN 
		),
		WEEE_PRIVILEGE_NORMAL_ADMIN => array (
				META_CODE_USER_ROLE_DEAL_VIEWER,
				META_CODE_USER_ROLE_DEAL_ADMIN,
				META_CODE_USER_ROLE_DEAL_3RD_ADMIN,
				META_CODE_USER_ROLE_PURCHASER,
				META_CODE_USER_ROLE_WAREHOUSE_VIEWER,
				META_CODE_USER_ROLE_WAREHOUSE_KEEPER,
				META_CODE_USER_ROLE_ACCOUNTING,
				META_CODE_USER_ROLE_ARTICLE_ADMIN,
				META_CODE_USER_ROLE_CS_AGENT,
				META_CODE_USER_ROLE_CS_MANAGER,
				META_CODE_USER_ROLE_MANAGER,
				META_CODE_USER_ROLE_SYSTEM_ADMIN 
		),
		WEEE_PRIVILEGE_MAIN_DATA_ADMIN => array (
				META_CODE_USER_ROLE_MAIN_DATA_ADMIN 
		),
		WEEE_PRIVILEGE_DEAL_VIEW => array (
				META_CODE_USER_ROLE_DEAL_VIEWER,
				META_CODE_USER_ROLE_DEAL_ADMIN,
				META_CODE_USER_ROLE_ACCOUNTING,
				META_CODE_USER_ROLE_PURCHASER,
				META_CODE_USER_ROLE_MANAGER,
				META_CODE_USER_ROLE_SYSTEM_ADMIN 
		),
		WEEE_PRIVILEGE_DEAL_ADMIN => array (
				META_CODE_USER_ROLE_DEAL_ADMIN,
				META_CODE_USER_ROLE_MANAGER,
				META_CODE_USER_ROLE_SYSTEM_ADMIN 
		),
		WEEE_PRIVILEGE_PURCHASE_ADMIN => array (
				META_CODE_USER_ROLE_PURCHASER,
				META_CODE_USER_ROLE_MANAGER 
		),
		WEEE_PRIVILEGE_WAREHOUSE_VIEWER => array (
				META_CODE_USER_ROLE_WAREHOUSE_VIEWER,
				META_CODE_USER_ROLE_WAREHOUSE_KEEPER,
				META_CODE_USER_ROLE_PURCHASER,
				META_CODE_USER_ROLE_MANAGER,
				META_CODE_USER_ROLE_SYSTEM_ADMIN 
		),
		WEEE_PRIVILEGE_WAREHOUSE_ADMIN => array (
				META_CODE_USER_ROLE_WAREHOUSE_KEEPER,
				META_CODE_USER_ROLE_MANAGER,
				META_CODE_USER_ROLE_SYSTEM_ADMIN 
		),
		WEEE_PRIVILEGE_ARTICLE_ADMIN => array (
				META_CODE_USER_ROLE_ARTICLE_ADMIN,
				META_CODE_USER_ROLE_MANAGER,
				META_CODE_USER_ROLE_SYSTEM_ADMIN 
		),
		WEEE_PRIVILEGE_DEAL_3RD_ADMIN => array (
				META_CODE_USER_ROLE_DEAL_3RD_ADMIN,
				META_CODE_USER_ROLE_MANAGER,
				META_CODE_USER_ROLE_SYSTEM_ADMIN 
		),
		WEEE_PRIVILEGE_DEAL_3RD_VENDOR_VOUCHER => array (
				META_CODE_USER_ROLE_DEAL_3RD_ADMIN,
				META_CODE_USER_ROLE_ACCOUNTING,
				META_CODE_USER_ROLE_SYSTEM_ADMIN 
		),
		WEEE_PRIVILEGE_DEAL_ACCOUNTING => array (
				META_CODE_USER_ROLE_ACCOUNTING,
				META_CODE_USER_ROLE_SYSTEM_ADMIN 
		),
		WEEE_PRIVILEGE_INVOICE_MANAGEMENT => array (
				META_CODE_USER_ROLE_ACCOUNTING,
				META_CODE_USER_ROLE_WAREHOUSE_KEEPER,
				META_CODE_USER_ROLE_MANAGER,
				META_CODE_USER_ROLE_SYSTEM_ADMIN 
		),
		WEEE_PRIVILEGE_POINTS_CREATE => array (
				META_CODE_USER_ROLE_CS_AGENT,
				META_CODE_USER_ROLE_ACCOUNTING,
				META_CODE_USER_ROLE_SYSTEM_ADMIN 
		),
		WEEE_PRIVILEGE_POINTS_ADMIN => array (
				META_CODE_USER_ROLE_MANAGER,
				META_CODE_USER_ROLE_CS_MANAGER,
				META_CODE_USER_ROLE_SYSTEM_ADMIN 
		),
		WEEE_PRIVILEGE_POINTS_VIEW => array (
				META_CODE_USER_ROLE_CS_AGENT,
				META_CODE_USER_ROLE_ACCOUNTING,
				META_CODE_USER_ROLE_MANAGER,
				META_CODE_USER_ROLE_CS_MANAGER,
				META_CODE_USER_ROLE_SYSTEM_ADMIN 
		),
		WEEE_PRIVILEGE_GB_RETURN_CREATE => array (
				META_CODE_USER_ROLE_CS_AGENT,
				META_CODE_USER_ROLE_SYSTEM_ADMIN 
		),
		WEEE_PRIVILEGE_GB_RETURN_ADMIN => array (
				META_CODE_USER_ROLE_CS_MANAGER,
				META_CODE_USER_ROLE_SYSTEM_ADMIN 
		),
		WEEE_PRIVILEGE_GB_RETURN_VIEW => array (
				META_CODE_USER_ROLE_CS_AGENT,
				META_CODE_USER_ROLE_CS_MANAGER,
				META_CODE_USER_ROLE_SYSTEM_ADMIN 
		),
		WEEE_PRIVILEGE_REPORT_VIEW => array (
				META_CODE_USER_ROLE_MANAGER 
		),
		WEEE_PRIVILEGE_CONFIG => array (
				META_CODE_USER_ROLE_MANAGER,
				META_CODE_USER_ROLE_SYSTEM_ADMIN 
		),
		WEEE_PRIVILEGE_INVOICE_CREATE => array (
				META_CODE_USER_ROLE_INVOICE_ADMIN 
		) 
);
